config/routes.php
<?php

use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    $routes->applyMiddleware('csrf');

    $routes->connect('/', ['controller' => 'Messages', 'action' => 'home']);

    // https://book.cakephp.org/3.0/en/development/routing.html#route-elements
    $routes->connect(
        ':id/message/:day/:month/:year/:slug',
        ['controller' => 'Messages', 'action' => 'details']
    )
        ->setPass(['id', 'day', 'month', 'year', 'slug'])
        ->setPatterns([
            'year' => '[12][0-9]{3}',
            'month' => '0[1-9]|1[012]',
            'day' => '0[1-9]|[12][0-9]|3[01]'
        ]);

    $routes->fallbacks(DashedRoute::class);
});

Router::scope('/api', function (RouteBuilder $routes) {
    $routes->setExtensions(['json', 'xml']);

    $routes->resources('Users', function (RouteBuilder $routes) {
        $routes->resources('Messages');
    });

    $routes->resources('Messages', function (RouteBuilder $routes) {
        $routes->resources('Replies');
    });

    $routes->resources('MessagesApi');
});

src/Model/Entity/Message.php
<?php

namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\Utility\Text;

class Message extends Entity
{
    protected function _setSubject($subject)
    {
        $this->slug = strtolower(Text::slug($subject));
        return $subject;
    }

    /**
     * Returns a comma separated list of user emails message was sent to.
     * Requires inbox.users to be loaded with the message.
     */
    protected function _getToDisplayList()
    {
        $to = '';
        foreach ($this->inbox as $inbox) {
            $to .= $inbox->Users['email'] ?? 'all';
            $to .= ', ';
        }

        return rtrim($to, ', ');
    }

    protected function _getPermalink()
    {
        $id = $this->id;
        $date = $this->created->format('d/m/Y');
        $slug = $this->slug;
        return "/$id/message/$date/$slug";
    }

    protected function _getDisplayDateSent()
    {
        return $this->created->format('F j, Y \a\t g:i a');
    }
}

src/Model/Entity/User.php
<?php

namespace App\Model\Entity;

use Cake\Auth\DefaultPasswordHasher;
use Cake\ORM\Entity;

class User extends Entity
{
    // https://book.cakephp.org/3.0/en/tutorials-and-examples/cms/authentication.html#adding-password-hashing
    protected function _setPassword($value)
    {
        if (strlen($value)) {
            $hasher = new DefaultPasswordHasher();
            return $hasher->hash($value);
        }
    }

    // https://book.cakephp.org/3.0/en/orm/entities.html#creating-virtual-properties
    protected function _getFullName()
    {
        return $this->first_name . '  ' . $this->last_name;
    }
}

src/Model/Table/MessagesTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;

class MessagesTable extends Table
{
    public function initialize(array $config)
    {
        $this->addBehavior('Timestamp');
        $this->belongsTo('Users');
        $this->hasMany('Inbox', ['dependent' => true]);
        $this->hasMany('Replies', ['dependent' => true]);
    }

    public function validationDefault(Validator $validator)
    {
        return $validator
            ->requirePresence('to')
            ->notEmpty('to')
            ->requirePresence('subject')
            ->notEmpty('subject', 'Subject cannot be left empty')
            ->maxLength('subject', 100, 'Subject cannot be longer than 100 characters')
            ->requirePresence('content')
            ->notEmpty('content', 'Message cannot be left empty')
            ->minLength('content', 20, 'Your message must be at least 20 characters')
            ->maxLength('content', 2000, 'Your message cannot be longer than 2000 characters');
    }

    // https://book.cakephp.org/3.0/en/tutorials-and-examples/blog-auth-example/auth.html
    public function isOwnedBy($messageId, $userId)
    {
        return $this->exists(['id' => $messageId, 'user_id' => $userId]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\Http\Exception\NotFoundException;
use App\Model\Entity\Message;
use Cake\Http\Exception\BadRequestException;
use Cake\Log\Log;
use Cake\Filesystem\File;

class MessagesController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->Auth->allow(['add', 'home', 'index']);
        $this->loadComponent('RequestHandler');
    }

    // https://book.cakephp.org/3.0/en/tutorials-and-examples/blog-auth-example/auth.html
    public function isAuthorized($user)
    {
        $action = $this->request->action;

        // All registered users can view inbox and sent messages
        if (in_array($action, ['inbox', 'sent'])) {
            return true;
        }

        if ($action == 'details') {
            $message = TableRegistry::get('Messages')->get($this->request->id);

            if ($message->user_id == $this->Auth->user('id')) {
                return true;
            }

            if (TableRegistry::get('Inbox')->isGlobal($message->id)) {
                return true;
            }

            if (TableRegistry::get('Inbox')->isInUserInbox($message->id, $user['id'])) {
                return true;
            }

            if (!parent::isAuthorized($user)) {
                $this->logMessageAccessError($message);
                return false;
            }

            return true;
        }

        return parent::isAuthorized($user);
    }

    private function getToArray()
    {
        $to = trim($this->request->data('to'));
        $to = trim($to, ',');
        return array_map('trim', explode(',', $to));
    }

    private function logMessageSuccess(Message $message)
    {
        if ($this->Auth->user()) {
            Log::info("User #{$this->Auth->user('id')} {$this->Auth->user('email')} [{$this->request->clientIp()}] sent message #{$message->id}", 'messages');
        } else {
            Log::info("Anonymous user [{$this->request->clientIp()}] sent message #{$message->id}", 'messages');
        }
    }

    private function logMessageError(string $to)
    {
        if ($this->Auth->user()) {
            Log::error("User #{$this->Auth->user('id')} {$this->Auth->user('email')} [{$this->request->clientIp()}] failed to send a message addressed to: $to", 'messages');
        } else {
            Log::error("Anonymous user [{$this->request->clientIp()}] failed to send message addressed to: $to", 'messages');
        }
    }

    private function add(Message $message)
    {
        $this->Messages->patchEntity($message, $this->request->getData());

        if ($message->hasErrors()) {
            $hint = 'Please amend your form and try again.';
            $hint .= '<ul class="mb-0">';
            foreach ($message->geterrors() as $key => $errorArray) {
                $e = reset($errorArray);
                $hint .= "<li>$e</li>";
            }
            $hint .= '</ul>';
            $this->Flash->error($hint, ['escape' => false]);
            return;
        }

        $message->user_id = $this->Auth->user('id');

        $to = trim($this->request->getData('to'));

        // if the user is anonymous or 'to' is set to 'all'
        if (!$this->Auth->user() || $to === 'all') {
            if (!TableRegistry::get('Inbox')->sendToAll($message)) {
                $this->logMessageError($to);
                $this->Flash->error('Message failed to send. Please try again later.');
                return;
            }
        }
        // if user is authenticated and to is not set to all
        else {
            if (!TableRegistry::get('Inbox')->sendToEmails($this->getToArray(), $message)) {
                $this->logMessageError($to);
                $this->Flash->error('Message failed to send. Please try again later.');
                return;
            }
        }

        $imageName = $this->saveImage($this->request->getData('image'), $message->id);
        if ($imageName) {
            $message->attachment_path = $imageName;
            $this->Messages->save($message);
        }

        $this->logMessageSuccess($message);
        $this->Flash->success('Message sent successfully.');
        return $this->redirect(['action' => 'home']);
    }

    private function saveImage(array $image, int $messageId)
    {
        $src = $image['tmp_name'];
        if (!$src) {
            return false;
        }
        
        $newName = $messageId . '_' . $image['name'];
        $dest = WWW_ROOT . 'img' . DS . $newName;
        $moved = move_uploaded_file($src, $dest);
        if (!$moved) {
            return false;
        }

        return $newName;
    }

    public function home()
    {
        $message = $this->Messages->newEntity();

        if ($this->request->isPost()) {
            $this->add($message);
        }

        $global = TableRegistry::get('Inbox')->find()
            ->where(function ($exp, $q) {
                return $exp->isNull('Inbox.user_id');
            })
            ->contain(['Messages.Users'])
            ->orderDesc('Messages.created')
            ->toArray();

        $this->set([
            'user' => $this->Auth->user(),
            'global' => $global,
            'message' => $message
        ]);
    }

    public function inbox()
    {
        $inbox = TableRegistry::get('Inbox')
            ->find()
            ->contain(['Messages.Users'])
            ->where(['Inbox.user_id' => $this->Auth->user('id')])
            ->orderDesc('Messages.created')
            ->toArray();

        $this->set('inbox', $inbox);
    }

    public function sent()
    {
        $user = TableRegistry::get('Users')->findByIdWithSentMessages($this->Auth->user('id'));
        $this->set('sent', $user->messages);
    }

    private function logMessageAccessSuccess(Message $message)
    {
        Log::info("User #{$this->Auth->user('id')} {$this->Auth->user('email')} [{$this->request->clientIp()}] accessed message #{$message->id}", 'messages');
    }

    private function logMessageAccessError(Message $message)
    {
        if ($this->Auth->user()) {
            Log::warning("User #{$this->Auth->user('id')} {$this->Auth->user('email')} [{$this->request->clientIp()}] tried accessing message #{$message->id}", 'messages');
        } else {
            Log::warning("Anonymous user [{$this->request->clientIp()}] tried accessing message #{$message->id}", 'messages');
        }
    }

    public function details($id, $day, $month, $year, $slug)
    {
        $message = TableRegistry::get('Messages')->get($id, [
            'contain' => [
                'Users',
                'Replies' => ['sort' => ['Replies.created' => 'DESC']],
                'Replies.Users'
            ]
        ]);

        if (empty($message)) {
            throw new NotFoundException;
        }

        $this->set([
            'user' => $this->Auth->user(),
            'message' => $message
        ]);

        $this->logMessageAccessSuccess($message);
    }

    public function delete($id)
    {
        $this->request->allowMethod(['post', 'delete']);

        $message = $this->Messages->get($id);

        if ($message->attachment_path) {
            $file = new File(WWW_ROOT . 'img' . DS . $message->attachment_path);
            $file->delete();
        }
        
        if ($this->Messages->delete($message)) {
            $this->Flash->success('This message has been deleted.');
        } else {
            $this->Flash->error('Failed deleting message. Please try again later.');
        }

        return $this->redirect(['action' => 'home']);
    }

    // API endpoints

    /**
     * Get list of messages and their replies sent by a specific user (HTTP GET)
     * 
     * url: api/users/123/messages.json
     */
    public function index()
    {
        $userId = $this->request->getParam('user_id');

        if (!$userId) {
            throw new BadRequestException('Viewing all messages not supported. Please provide user id.');
        }

        $message = $this->Messages
            ->find()
            ->where(['user_id' => $userId])
            ->contain('Replies');

        $this->set([
            'message' => $message,
            '_serialize' => ['message']
        ]);
    }
}

src/Template/Messages/details.ctp
<?php $this->assign('title', h($message->subject)); ?>
<?php $author = $message->user ?>
<?php $image = $message->attachment_path ?>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <?= $this->Flash->render() ?>

        <div class="card px-5 py-3">
            <div class="card-body" >
                <h2 class="display-4" style="font-size:2rem;"><?= h($message->subject) ?></h2>
                <p class="text-muted" style="margin-top: -8px; font-size: 14px">
                    by <strong>
                        <?= isset($author) ? $author->full_name : 'anonymous' ?>
                        <?php if ($author->role === 'admin') : ?>
                        <span class="badge badge-danger" style="font-size:.8rem;">admin</span>
                        <?php endif; ?>
                    </strong>
                    on <?= $message->display_date_sent ?>
                </p>
                <p><?= h($message->content) ?></p>
                <?php if ($image): ?>
                <div class="px-4">
                    <img
                        src="<?= $this->Url->build("/img/$image") ?>"
                        class="img-fluid mb-3"
                    />
                </div>
                <?php endif; ?>
                <?php if ($user['role'] == 'admin') : ?>
                <div class="text-right">
                    <button class="btn btn__delete-reply--light" onclick="showDeleteAlert(this);">Delete</button>
                    <?= $this->Form->create(null, [
                        'url' => ['controller' => 'Messages', 'action' => 'delete', $message->id],
                        'style' => 'display: none;'
                    ]) ?>
                    <?= $this->Form->end() ?>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div class="row my-3">
    <div class="col-md-8 offset-md-2">
        <h5 class="my-3">
            Post a reply 
            <small class="text-muted">as <?= $user['first_name'] ?> <?= $user['last_name'] ?>
                <?php if ($user['role'] === 'admin') : ?>
                <span class="badge badge-danger" style="font-size:.8rem;">admin</span>
                <?php endif; ?>
            </small>
        </h5>

        <?= $this->Form->create(null, [
            'url' => ['controller' => 'Replies', 'action' => 'Add']
        ]) ?>
            <input name="message_id" type="hidden" value="<?= $message->id ?>">
            <div class="form-group">
                <textarea name="content" class="form-control" rows="5"></textarea>
            </div>
            <div class="form-group text-right">
                <button type="submit" class="btn btn-outline-primary">Reply</button>
            </div>
        <?= $this->Form->end() ?>

        <h5 id="discussion">Discussion</h5>
        <?php if (empty($message->replies)) : ?>
        <p class="text-muted mt-4">
            <i class="far fa-lightbulb text-warning"></i> Replies to this message will appear here.
        </p>
        <?php endif; ?>

        <?php foreach ($message->replies as $reply) : ?>
        <div class="py-5" style="border-bottom: 2px solid hsla(212, 56%, 16%, 0.2);">
            <h6 class="card-title mb-0"><?= $reply->user->full_name ?>
                <?php if ($reply->user['role'] === 'admin') : ?>
                <span class="badge badge-danger" style="font-size:.8rem;">admin</span>
                <?php endif; ?>
            </h6>
            <small class="text-muted"><?= $reply->created->format('F j, Y \a\t g:i a') ?></small>
            <p class="card-text mt-2"><?= h($reply->content) ?></p>
            <?php if ($reply->user_id == $user['id'] || $user['role'] == 'admin') : ?>
            <div class="text-right">
                <button class="btn btn__delete-reply" onclick="showDeleteAlert(this);">Delete</button>
                <?= $this->Form->create(null, [
                    'url' => ['controller' => 'Replies', 'action' => 'delete', $reply->id],
                    'style' => 'display: none;'
                ]) ?>
                <?= $this->Form->end() ?>
            </div>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>

<?php $this->start('script'); ?>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    // https://sweetalert.js.org/guides/
    function showDeleteAlert(button) {
        swal({
            title: 'Are you sure?',
            text: 'Once deleted, there is no undo!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {
                button.nextElementSibling.submit();
            } else {
                swal("Delete cancelled!", {
                    icon: "error"
                });
            }
        });
    }
</script>
<?php $this->end(); ?>

src/Template/Messages/home.ctp
<?php $this->assign('title', 'Home'); ?>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <?= $this->Flash->render() ?>

        <h4 class="mt-3 mb-4 display-4" style="font-size: 2rem;">
            Send message
            <small class="text-muted">as <?= $user['email'] ?? 'anonymous' ?>
                <?php if ($user['role'] === 'admin') : ?>
                <span class="badge badge-danger" style="font-size:.9rem;">admin</span>
                <?php endif; ?>
            </small>
        </h4>
        <?= $this->Form->create($message, ['type' => 'file', 'novalidate' => true]) ?>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">To</div>
                    </div>
                    <?php if ($user) : ?>
                    <?= $this->Form->text('to', [
                        'class' => 'form-control',
                        'placeholder' => 'Recipients'
                    ]) ?>
                    <?php else : ?>
                    <?= $this->Form->text('to', [
                        'class' => 'form-control',
                        'placeholder' => 'Recipients',
                        'readonly',
                        'value' => 'all'
                    ]) ?>
                    <?php endif; ?>
                </div>
                <?php if ($user) : ?>
                <small class="form-text text-muted">
                    Enter a comma separated list of emails, or 'all' to target everyone.
                </small>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <?= $this->Form->text('subject', [
                    'class' => 'form-control',
                    'placeholder' => 'Add a subject'
                ]) ?>
            </div>
            <div class="form-group">
                <?= $this->Form->textarea('content', [
                    'class' => 'form-control',
                    'rows' => 7,
                    'placeholder' => 'Add a message'
                ]) ?>
            </div>
            <div class="form-group">
                <label for="image">Image Attachment (optional)</label>
                <?= $this->Form->file('image', [
                    'class' => 'form-control-file'
                ]); ?>
            </div>
            <div class="form-group text-right">
                <button type="submit" class="btn btn-outline-primary">Send Message</button>
            </div>
        <?= $this->Form->end() ?>
    </div>
</div>

<div class="row my-2">
    <div class="col-md-8 offset-md-2">
        <h4 id="psa" class="display-4" style="font-size: 1.75rem;">Public Announcements</h4>

        <?php if (empty($global)) : ?>
        <p class="text-muted mt-4">
            <i class="far fa-lightbulb text-warning"></i> Public announcements will appear here.
        </p>
        <?php endif; ?>

        <?php foreach ($global as $inbox) : ?>
        <?php $message = $inbox->message ?>
        <?php $author = $message->user ?>
        <div class="card my-4">
            <div class="card-body p-4">
                <h4 class="card-title mb-0">
                    <?= h($message->subject) ?>
                </h4>
                <small class="text-muted">
                    by <strong><?= isset($author)
                        ? ($user['role'] === 'admin'
                            ? "<a href='{$this->Url->build("/users/messages/$author->id")}' class='card-link'>$author->full_name</a>"
                            : $author->full_name)
                        : 'anonymous' ?></strong>
                    <?php if ($author->role === 'admin') : ?>
                    <span class="badge badge-danger" style="font-size:.7rem;">admin</span>
                    <?php endif; ?>
                    on <?= $message->display_date_sent ?>
                </small>
                <p class="card-text mt-3"><?= h($message->content) ?></p>
            </div>
            <div class="card__footer p-3">
                <a href="<?= $this->Url->build($message->permalink) ?>" class="btn">
                    <i class="fas fa-envelope-open"></i> View Message
                </a>
                <a href="<?= $this->Url->build($message->permalink) ?>#discussion" class="btn">
                    <i class="fas fa-comments"></i>
                    <?= $message->reply_count == 0
                        ? 'Reply'
                        : ($message->reply_count == 1
                            ? "1 Reply"
                            : "$message->reply_count Replies") ?>
                </a>
                <?php if ($user['role'] == 'admin') : ?>
                <button class="btn card-link btn-link" onclick="showDeleteAlert(this);">
                    <i class="fas fa-trash"></i> Delete
                </button>
                <?= $this->Form->create(null, [
                    'url' => ['controller' => 'Messages', 'action' => 'delete', $message->id],
                    'style' => 'display: none;'
                ]) ?>
                <?= $this->Form->end() ?>
                <?php endif; ?>
            </div>
        </div>
        <?php endforeach ?>
    </div>
</div>

<?php $this->start('script'); ?>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    // https://sweetalert.js.org/guides/
    function showDeleteAlert(button) {
        swal({
            title: 'Are you sure?',
            text: 'Once deleted, there is no undo!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {
                button.nextElementSibling.submit();
            } else {
                swal("Delete cancelled!", {
                    icon: "error"
                });
            }
        });
    }
</script>
<?php $this->end(); ?>

src/Template/Messages/inbox.ctp
<?php $this->assign('title', 'Inbox'); ?>

<div class="row my-2">
    <div class="col-md-8 offset-md-2">
        <?= $this->Flash->render() ?>
        <h4 class="mt-3 mb-4 display-4" style="font-size:2rem;">Inbox</h4>

        <?php if (empty($inbox)) : ?>
        <p class="text-muted">
            <i class="far fa-lightbulb text-warning"></i> Messages sent directly to you will appear here.
        </p>
        <?php endif; ?>

        <?php foreach ($inbox as $in) : ?>
        <?php $message = $in->message ?>
        <div class="card my-4">
            <div class="card-body">
                <h5 class="card-title mb-0">
                    <a href="<?= $this->Url->build($message->permalink) ?>" class="card-link">
                        <?= h($message->subject) ?>
                    </a>
                </h5>
                <small class="text-muted">
                    by
                    <strong>
                        <?= $message->user->email ?>
                        <?php if ($message->user->role === 'admin') : ?>
                        <span class="badge badge-danger" style="font-size:.8rem;">admin</span>
                        <?php endif; ?>
                    </strong>
                    on <?= $message->display_date_sent ?>
                </small>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>

src/Template/Messages/sent.ctp
<?php $this->assign('title', 'Sent'); ?>

<div class="row my-2">
    <div class="col-md-8 offset-md-2">
        <?= $this->Flash->render() ?>
        <h4 class="mt-3 mb-4 display-4" style="font-size:2rem;">Sent</h4>

        <?php if (empty($sent)) : ?>
        <p class="text-muted">
            <i class="far fa-lightbulb text-warning"></i> Messages sent by you will appear here.
        </p>
        <?php endif; ?>

        <?php foreach ($sent as $message) : ?>
        <div class="card my-4">
            <div class="card-body">
                <h5 class="card-title mb-0">
                    <a href="<?= $this->Url->build($message->permalink) ?>" class="card-link">
                        <?= h($message->subject) ?>
                    </a>
                </h5>
                <small class="text-muted">
                    to <strong><?= $message->to_display_list ?></strong>
                    on <?= $message->display_date_sent ?>
                </small>
            </div>
        </div>
        <?php endforeach ?>
    </div>
</div>